<script type="text/javascript" src="<?= $block->getViewFileUrl('js/App.js') ?>"></script>
<h1> Tipos de Pokemones de la Generación I</h1>
<?php
$data = $block->getAllTypes();
?>
<table class="pokemon-table">
  <tr>
    <th class="post-id">ID</th>
    <th class="post-id">Tipos</th>
    <th class="post-name">URL</th>
  </tr>
  <?php
  foreach ($data as $key => $post) {
    echo '<tr>
                    <td>' . ($key + 1) . '</td>
                    <td>' . $post['name'] . '</td>
                    <td>
                      <form action="/taskthird/third/types" method="get">
                        <input type="text" id="' . $post['name'] . '" name="type" value="type" hidden >
                        <input type="text" id="' . $post['url'] . '" name="id" value ="' . $block->getExtId($post['url']) . '" hidden>
                        <button id="b-ver" type="submit">Ver</button>
                      </form>
                    </td>
                  </tr>';
  }
  ?>
</table>
<!-- <div id="app">
  <h1>Tipos de Pokemones de la Generación I</h1>

  <table class="pokemon-table">
    <tr>
      <th class="post-id">ID</th>
      <th class="post-id">Tipos</th>
      <th class="post-name">URL</th>
    </tr>
    <tr v-for="(post, index) in phpData" :key="index">
      <td>{{ index + 1 }}</td>
      <td>{{ post.name }}</td>
      <td>
        <form @submit.prevent="viewType(post.url)">
          
          <script>
            var serializedFunction = <?php echo $block->getExtId('post.url'); ?>;
            //console.log(serializedFunction);
          </script>
          <input type="text" id="{{post.name}}" name="type" value="type" hidden>
          <input type="text" id="{{post.url}}" name="id" value="<?php $block->getExtId('{{post.url}}') ?>">
          <button id="b-ver" type="submit">Ver</button>
        </form>
      </td>
    </tr>
  </table>
  <p>{{ result }}</p>
</div> -->

<script>
  //var phpData = <?= json_encode($data) ?>;

  //console.log(phpData);
/*
  fetch('/third.php')
  .then(response => response.json())
  .then(data => {
    // Aquí puedes trabajar con los datos recibidos desde el backend
    console.log(data);
    console.log('hola mundo');
  })
  .catch(error => {
    console.error('Error:', error);
  });*/

</script>