<h1> Welcome to Tasksecond Templates</h1>

<?php $value = $block->getFlag(false) ? "OK" : "NO";?>

<h2> El valor recibido es : <?php echo 'valor '.$value; ?> </h2>


<div id="app" data-valor="<?php echo $value; ?>">
<hr>
<span>datos desde vue.js</span>
<br>
<button v-on:click="changeResp" id="changeResp">Cambiar Vista</button>

<h2>El valor recibido es: {{ respuesta }}</h2>

<div v-if="respuesta === 'OK'">
    <!-- Vista cuando el valor es "OK" -->
    <h3>Esta es la vista OK </h3>
    <h2>vista ok</h2>
    <h4>ok</h4>
  </div>
  <div v-else>
    <!-- Vista cuando el valor es "NO" -->
    <h3>Esta es la vista NO</h3>

    <h6>sssssss</h6>

    <span>hola a todos</span>
  </div>
</div>